---
- name: reload systemd
  systemd:
    daemon_reload: yes

- name: sequentially restart kong
  # `serial: 1` would be the proper solution here, but that can only be set on play level (upstream issue: https://github.com/ansible/ansible/issues/12170)
  run_once: true
  with_items: "{{ play_hosts }}"
  delegate_to: "{{ item }}"
  shell: systemctl restart kong && sleep {{ kong_sleep_between_restarts }}

- name: sequentially reload kong
  # `serial: 1` would be the proper solution here, but that can only be set on play level (upstream issue: https://github.com/ansible/ansible/issues/12170)
  run_once: true
  with_items: "{{ play_hosts }}"
  delegate_to: "{{ item }}"
  shell: systemctl reload kong && sleep {{ kong_sleep_between_reloads }}